# Generated by Django 5.2.7 on 2025-11-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('steps', models.JSONField(default=list)),
                ('ingredients_list', models.JSONField(default=list)),
                ('protein_percent', models.FloatField(default=0.0)),
                ('fat_percent', models.FloatField(default=0.0)),
                ('carbs_percent', models.FloatField(default=0.0)),
                ('avg_sugar_g', models.FloatField(default=0.0)),
                ('avg_fiber_g', models.FloatField(default=0.0)),
                ('cluster', models.IntegerField()),
                ('cluster_name', models.CharField(max_length=100)),
                ('avg_calories', models.FloatField(default=0.0)),
                ('avg_protein_g', models.FloatField(default=0.0)),
                ('avg_fat_g', models.FloatField(default=0.0)),
                ('avg_carbs_g', models.FloatField(default=0.0)),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
    ]
