# Generated by Django 5.2.7 on 2025-11-03 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='meal_type',
            field=models.CharField(default='Unknown', max_length=50),
        ),
    ]
