# Generated by Django 5.2.7 on 2025-11-06 13:36

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('planner', '0002_recipe_meal_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanGenerationEvent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('primary_goal', models.CharField(choices=[('lose_weight', 'Lose Weight'), ('maintain', 'Maintain Weight'), ('gain_muscle', 'Gain Muscle')], max_length=20, verbose_name='Primary Goal')),
                ('pace', models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('fast', 'Fast')], max_length=20, verbose_name='Pace')),
                ('weight_kg_at_request', models.FloatField(validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(300.0)], verbose_name='Weight (kg) at Request')),
                ('calculated_targets', models.JSONField(default=dict, help_text='Calculated nutritional targets (calories, protein_g, fat_g, carbs_g)', verbose_name='Calculated Targets')),
                ('predicted_cluster_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Predicted Cluster Name')),
                ('status', models.CharField(choices=[('success', 'Success'), ('fallback_default', 'Fallback Default'), ('failed', 'Failed'), ('infeasible', 'Infeasible'), ('timeout', 'Timeout')], default='success', max_length=20, verbose_name='Status')),
                ('number_of_days', models.IntegerField(default=7, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='Number of Days')),
            ],
            options={
                'verbose_name': 'Plan Generation Event',
                'verbose_name_plural': 'Plan Generation Events',
                'db_table': 'planner_plangenerationevent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True, verbose_name='Gender')),
                ('height_cm', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(300.0)], verbose_name='Height (cm)')),
                ('activity_level', models.CharField(choices=[('sedentary', 'Sedentary'), ('light', 'Light'), ('moderate', 'Moderate'), ('active', 'Active'), ('very_active', 'Very Active')], default='moderate', max_length=20, verbose_name='Activity Level')),
                ('allergies', models.JSONField(blank=True, default=list, help_text='List of allergies (e.g., ["peanuts", "shellfish"])', verbose_name='Allergies')),
                ('dislikes', models.JSONField(blank=True, default=list, help_text='List of disliked foods (e.g., ["lamb", "bitter melon"])', verbose_name='Dislikes')),
                ('dietary_preferences', models.CharField(choices=[('none', 'None'), ('vegetarian', 'Vegetarian'), ('vegan', 'Vegan'), ('pescatarian', 'Pescatarian'), ('keto', 'Keto'), ('paleo', 'Paleo'), ('mediterranean', 'Mediterranean')], default='none', max_length=20, verbose_name='Dietary Preferences')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
                'db_table': 'planner_userprofile',
            },
        ),
        migrations.CreateModel(
            name='GeneratedPlan',
            fields=[
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='generated_plan', serialize=False, to='planner.plangenerationevent', verbose_name='Plan Generation Event')),
                ('plan_data', models.JSONField(default=dict, help_text='Complete multi-day meal plan structure (Day 1, Day 2, etc.)', verbose_name='Plan Data')),
                ('final_nutritional_summary', models.JSONField(default=dict, help_text='Actual nutritional totals of the generated plan', verbose_name='Final Nutritional Summary')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Generated Plan',
                'verbose_name_plural': 'Generated Plans',
                'db_table': 'planner_generatedplan',
            },
        ),
        migrations.AddField(
            model_name='plangenerationevent',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_generation_events', to='planner.userprofile', verbose_name='User Profile'),
        ),
    ]
