# Generated by Django 5.2.7 on 2025-11-06 14:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_plangenerationevent_userprofile_generatedplan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedplan',
            name='final_nutritional_summary',
            field=models.JSONField(blank=True, default=dict, help_text='Actual nutritional totals of the generated plan', verbose_name='Final Nutritional Summary'),
        ),
        migrations.AlterField(
            model_name='plangenerationevent',
            name='calculated_targets',
            field=models.JSONField(blank=True, default=dict, help_text='Calculated nutritional targets (calories, protein_g, fat_g, carbs_g)', verbose_name='Calculated Targets'),
        ),
        migrations.AlterField(
            model_name='plangenerationevent',
            name='pace',
            field=models.CharField(choices=[('mild', 'Mild'), ('moderate', 'Moderate'), ('fast', 'Fast')], default='moderate', max_length=20, verbose_name='Pace'),
        ),
        migrations.AlterField(
            model_name='plangenerationevent',
            name='weight_kg_at_request',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(20.0), django.core.validators.MaxValueValidator(300.0)], verbose_name='Weight (kg) at Request'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='height_cm',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(50.0), django.core.validators.MaxValueValidator(250.0)], verbose_name='Height (cm)'),
        ),
    ]
