# Generated by Django 5.2.7 on 2025-11-07 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_alter_generatedplan_final_nutritional_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Optional: Enter your phone number (e.g., +1234567890)', max_length=20, null=True, verbose_name='Phone Number'),
        ),
    ]
